export default[
  {
    "login": "Md-Abdul-Hameed",
    "id": 56424328,
    "node_id": "MDQ6VXNlcjU2NDI0MzI4",
    "avatar_url": "https://avatars.githubusercontent.com/u/56424328?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Md-Abdul-Hameed",
    "html_url": "https://github.com/Md-Abdul-Hameed",
    "followers_url": "https://api.github.com/users/Md-Abdul-Hameed/followers",
    "following_url": "https://api.github.com/users/Md-Abdul-Hameed/following{/other_user}",
    "gists_url": "https://api.github.com/users/Md-Abdul-Hameed/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Md-Abdul-Hameed/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Md-Abdul-Hameed/subscriptions",
    "organizations_url": "https://api.github.com/users/Md-Abdul-Hameed/orgs",
    "repos_url": "https://api.github.com/users/Md-Abdul-Hameed/repos",
    "events_url": "https://api.github.com/users/Md-Abdul-Hameed/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Md-Abdul-Hameed/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "abdul-imad",
    "id": 60748865,
    "node_id": "MDQ6VXNlcjYwNzQ4ODY1",
    "avatar_url": "https://avatars.githubusercontent.com/u/60748865?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/abdul-imad",
    "html_url": "https://github.com/abdul-imad",
    "followers_url": "https://api.github.com/users/abdul-imad/followers",
    "following_url": "https://api.github.com/users/abdul-imad/following{/other_user}",
    "gists_url": "https://api.github.com/users/abdul-imad/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/abdul-imad/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/abdul-imad/subscriptions",
    "organizations_url": "https://api.github.com/users/abdul-imad/orgs",
    "repos_url": "https://api.github.com/users/abdul-imad/repos",
    "events_url": "https://api.github.com/users/abdul-imad/events{/privacy}",
    "received_events_url": "https://api.github.com/users/abdul-imad/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "shahzeb-mehdi",
    "id": 73132171,
    "node_id": "MDQ6VXNlcjczMTMyMTcx",
    "avatar_url": "https://avatars.githubusercontent.com/u/73132171?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/shahzeb-mehdi",
    "html_url": "https://github.com/shahzeb-mehdi",
    "followers_url": "https://api.github.com/users/shahzeb-mehdi/followers",
    "following_url": "https://api.github.com/users/shahzeb-mehdi/following{/other_user}",
    "gists_url": "https://api.github.com/users/shahzeb-mehdi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/shahzeb-mehdi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/shahzeb-mehdi/subscriptions",
    "organizations_url": "https://api.github.com/users/shahzeb-mehdi/orgs",
    "repos_url": "https://api.github.com/users/shahzeb-mehdi/repos",
    "events_url": "https://api.github.com/users/shahzeb-mehdi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/shahzeb-mehdi/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Salahuddin591",
    "id": 79139332,
    "node_id": "MDQ6VXNlcjc5MTM5MzMy",
    "avatar_url": "https://avatars.githubusercontent.com/u/79139332?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Salahuddin591",
    "html_url": "https://github.com/Salahuddin591",
    "followers_url": "https://api.github.com/users/Salahuddin591/followers",
    "following_url": "https://api.github.com/users/Salahuddin591/following{/other_user}",
    "gists_url": "https://api.github.com/users/Salahuddin591/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Salahuddin591/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Salahuddin591/subscriptions",
    "organizations_url": "https://api.github.com/users/Salahuddin591/orgs",
    "repos_url": "https://api.github.com/users/Salahuddin591/repos",
    "events_url": "https://api.github.com/users/Salahuddin591/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Salahuddin591/received_events",
    "type": "User",
    "site_admin": false
  }
]