export default{
  "login": "md-qubais",
  "id": 79993269,
  "node_id": "MDQ6VXNlcjc5OTkzMjY5",
  "avatar_url": "https://avatars.githubusercontent.com/u/79993269?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/md-qubais",
  "html_url": "https://github.com/md-qubais",
  "followers_url": "https://api.github.com/users/md-qubais/followers",
  "following_url": "https://api.github.com/users/md-qubais/following{/other_user}",
  "gists_url": "https://api.github.com/users/md-qubais/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/md-qubais/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/md-qubais/subscriptions",
  "organizations_url": "https://api.github.com/users/md-qubais/orgs",
  "repos_url": "https://api.github.com/users/md-qubais/repos",
  "events_url": "https://api.github.com/users/md-qubais/events{/privacy}",
  "received_events_url": "https://api.github.com/users/md-qubais/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Mohammed Qubaisuddin",
  "company": "QuantaVid LLC",
  "blog": "https://www.linkedin.com/in/mohammed-qubaisuddin-518b66182/",
  "location": "Hyderabad",
  "email": null,
  "hireable": null,
  "bio": "full stack software engineer",
  "twitter_username": "Qubais4",
  "public_repos": 39,
  "public_gists": 0,
  "followers": 4,
  "following": 5,
  "created_at": "2021-03-03T16:13:43Z",
  "updated_at": "2021-12-17T13:17:19Z"
}